<?php
// $Id: twocol.inc,v 1.1.2.3 2010/06/22 15:54:25 merlinofchaos Exp $

// Plugin definition
$plugin = array(
  'title' => t('Wide Right 2'),
  'category' => t('Columns: 2'),
  'icon' => 'wideright2.png',
  'theme' => 'wideright2',
  'css' => 'wideright2.css',
  'panels' => array(
    'wideright2_top' => t('wideright2 Top'),
    'wideright2_left' => t('wideright2 Left'),
    'wideright2_left2' => t('wideright2 Left 2'),
    'wideright2_central_top' => t('wideright2 Central Top'),
    'wideright2_central_mid_right' => t('wideright2 Central Mid Right'),
    'wideright2_central_mid_left' => t('wideright2 Central Mid Left'),
    'wideright2_central_mid2' => t('wideright2 Central Mid Lower'),
    'wideright2_central_bot' => t('wideright2 Central Bottom'),
    'wideright2_right' => t('wideright2 Right'),
  ),
);
